version: '3.8'

services:
  # Backend - .NET Core
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # Database
  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
    networks:
      - app_network

  # phpmyadmin
  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - "8090:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   networks:
      # - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db: